// Generated by CoffeeScript 1.6.3
(function() {
  var env, generate_mongo_url, mongo, mongourl;

  if (process.env.VCAP_SERVICES) {
    env = JSON.parse(process.env.VCAP_SERVICES);
    mongo = env['mongodb-1.8'][0]['credentials'];
  } else {
    mongo = {
      hostname: "localhost",
      port: 27017,
      username: "",
      password: "",
      name: "",
      db: "shoppingdb"
    };
  }

  generate_mongo_url = function(obj) {
    obj.hostname = obj.hostname || 'localhost';
    obj.port = obj.port || 27017;
    obj.db = obj.db || 'test';
    if (obj.username && obj.password) {
      return "mongodb://" + obj.username + ":" + obj.password + "@" + obj.hostname + ":" + obj.port;
    } else {
      return "mongodb://" + obj.hostname + ":" + obj.port;
    }
  };

  mongourl = process.env.MONGOLAB_URI || process.env.MONGOHQ_URL || generate_mongo_url(mongo);

  module.exports = mongourl;

}).call(this);
