// Generated by CoffeeScript 1.6.3
(function() {
  var cachedFiles, timestamp;

  cachedFiles = ['css/ratchet.css', 'css/style.css', 'js/app.js', 'js/main.js', 'js/controllers.js', 'js/directives.js', 'js/filters.js', 'js/services.js', 'js/lib/requirejs/require.min.js', 'js/lib/angular-unstable/angular.min.js', 'js/lib/underscore/underscore-min.js'];

  timestamp = new Date().toISOString();

  module.exports = {
    registerEndpoints: function(app) {
      return app.get('/app.cache', function(req, res) {
        console.log('app.cache with timestamp ', timestamp);
        return res.send('CACHE MANIFEST\n#' + timestamp + '\nCACHE:\n' + cachedFiles.join('\n') + '\nNETWORK:\n*');
      });
    },
    updateOfflineCache: function() {
      return timestamp = new Date().toISOString();
    }
  };

}).call(this);
