// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    registerEndpoints: function(app) {
      return app.get('/extension.crx', function(req, res) {
        res.header('Content-Type', 'application/do-not-install');
        return res.sendfile('IrmaTorvetExtension.crx', function(err) {
          if (err) {
            return console.log('Failed serving the extension: ' + err);
          }
        });
      });
    }
  };

}).call(this);
